name: domain
description: Domain package, which represents models and abstractions for Iteco Test app.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  lints: ^6.0.0
  test: ^1.28.0
