name: app
description: "A Flutter application as Iteco test task."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^11.0.0
  dio: ^5.9.0
  domain:
    path: ../domain
  elementary: ^3.2.1
  elementary_helper: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  json_annotation: ^4.9.0
  logger: ^2.6.0
  provider: ^6.1.5+1
  retrofit: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  json_serializable: ^6.10.0
  lints: ^6.0.0
  retrofit_generator: ^10.2.0
  test: ^1.28.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
flutter_intl:
  enabled: true
